name: Daisy
description: A GitHub action to automate running D.A.I.S.Y on a code repository
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  cwd:
    description: Sets the cwd for the node process. Default to `process.cwd()`
    required: false
  commit:
    description: |
      The commit message. Default to `D.A.I.S.Y updates`
    required: false
  title:
    description: The pull request title. Default to `D.A.I.S.Y updates`
    required: false
  setupGitUser:
    description: Sets up the git user for commits as `"github-actions[bot]"`. Default to `true`
    required: false
    default: true
outputs:
  memorized:
    description: A boolean value to indicate whether memorization happened or not
  documented:
    description: A boolean value to indicate whether documentation happened or not
  pullRequestNumber:
    description: The pull request number that was created or updated
branding:
  icon: "package"
  color: "blue"
