name: D.A.I.S.Y
description: A GitHub action to automate running D.A.I.S.Y on a code repository
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  setupGitUser:
    required: false
    default: true
outputs:
  memorized:
    description: A boolean value to indicate whether memorization happened or not
  documented:
    description: A boolean value to indicate whether documentation happened or not
  pullRequestNumber:
    description: The pull request number that was created or updated
branding:
  icon: "package"
  color: "blue"
